# Generated by Django 2.2.19 on 2021-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termandcondition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
